export default{
    name:"tabs",
    title:"Tabs",
    type:"document",
    fields:[
        {
            name:"title",
            title:"Title",
            type:"string"
        },
        {
            name:"path",
            title:"Path",
            type:"url"
        },
        {
            title:"Header",
            name:"header",
            type:"array",
            of:[{
                type:"header"
            }]
        },
        {
            title:"Items",
            name:"items",
            type:"array",
            of:[
                {
                    type:"tab"
                }
            ]
        },
        {
            name:"footer",
            title:"Footer",
            type:"array",
            of:[
                {
                    type:"footer"
                }
            ]
        }
    ]
}